'use strict';

export const CLIENT_STATUS_NEW_CLIENT_ID = 38000;
export const CLIENT_STATUS_RETURNING_CLIENT_ID = 38001;
export const CLIENT_STATUS_LOAN_TRANSFER_CLIENT_ID = 38002;
export const CLIENT_STATUS_LOAN_ON_GOING_CLIENT_ID = 38003;
