'use strict';

export const CLIENT_STATUS_NEW_CLIENT_ID = 38000;
export const CLIENT_STATUS_RETURNING_CLIENT_ID = 38001;
export const CLIENT_STATUS_LOAN_TRANSFER_CLIENT_ID = 38002;
export const CLIENT_STATUS_LOAN_ON_GOING_CLIENT_ID = 38003;
export const CLIENT_STATUS_LOAN_ACTION_CLIENT_ID = 38004;
export const ONLINE_VERIFICATION_STEP_ONE = 20;
export const ONLINE_VERIFICATION_STEP_TWO = 40;
export const ONLINE_VERIFICATION_STEP_THREE = 60;
export const ONLINE_VERIFICATION_STEP_FOUR = 80;
export const ONLINE_VERIFICATION_STEP_FIVE = 90;
export const ONLINE_VERIFICATION_STEP_SIX = 100;
