export const ONLINE_VERIFICATION_STEP_ONE = 20;
export const ONLINE_VERIFICATION_STEP_TWO = 40;
export const ONLINE_VERIFICATION_STEP_THREE = 60;
export const ONLINE_VERIFICATION_STEP_FOUR = 80;
export const ONLINE_VERIFICATION_STEP_FIVE = 90;
export const ONLINE_VERIFICATION_STEP_SIX = 100;
